/* eslint-disable comma-dangle */
/* eslint-disable indent */
/* eslint-disable quotes */
export default [
    { value: 0, label: 'ABAP', ace: 'abap', prism: null },
    { value: 1, label: 'ActionScript', ace: 'actionscript', prism: null },
    { value: 2, label: 'ADA', ace: 'ada', prism: null },
    { value: 3, label: 'Apache Conf', ace: 'apache_conf', prism: 'apacheconf' },
    { value: 4, label: 'AutoHotkey / AutoIt', ace: 'autohotkey', prism: null },
    { value: 5, label: 'AQL', ace: 'aql', prism: null },
    { value: 6, label: 'BatchFile', ace: 'batchfile', prism: 'batch' },
    { value: 7, label: 'Bro', ace: 'bro', prism: null },
    { value: 8, label: 'C', ace: 'c_cpp', prism: 'c' },
    { value: 9, label: 'C++', ace: 'c_cpp', prism: 'cpp' },
    { value: 10, label: 'C-Like', ace: 'c_cpp', prism: 'clike' },
    { value: 11, label: 'Crystal', ace: 'crystal', prism: null },
    { value: 12, label: 'Clojure', ace: 'clojure', prism: null },
    { value: 13, label: 'CoffeeScript', ace: 'coffee', prism: null },
    { value: 14, label: 'C#', ace: 'csharp', prism: null },
    { value: 15, label: 'CSS', ace: 'css', prism: null },
    { value: 16, label: 'D', ace: 'd', prism: null },
    { value: 17, label: 'Dart', ace: 'dart', prism: null },
    { value: 18, label: 'Diff', ace: 'diff', prism: null },
    { value: 19, label: 'Dockerfile', ace: 'dockerfile', prism: null },
    { value: 20, label: 'Eiffel', ace: 'eiffel', prism: null },
    { value: 21, label: 'EJS', ace: 'ejs', prism: null },
    { value: 22, label: 'Elixir', ace: 'elixir', prism: null },
    { value: 23, label: 'Elm', ace: 'elm', prism: null },
    { value: 24, label: 'Erlang', ace: 'erlang', prism: null },
    { value: 25, label: 'Fortran', ace: 'fortran', prism: null },
    { value: 26, label: 'FSharp', ace: 'fsharp', prism: null },
    { value: 27, label: 'Gcode', ace: 'gcode', prism: null },
    { value: 28, label: 'Gherkin', ace: 'gherkin', prism: null },
    { value: 29, label: 'Gitignore', ace: 'gitignore', prism: 'git' },
    { value: 30, label: 'Glsl', ace: 'glsl', prism: null },
    { value: 31, label: 'Go', ace: 'golang', prism: 'go' },
    {
        value: 32,
        label: 'GraphQLSchema',
        ace: 'graphqlschema',
        prism: 'graphql'
    },
    { value: 33, label: 'Groovy', ace: 'groovy', prism: null },
    { value: 34, label: 'HAML', ace: 'haml', prism: null },
    { value: 35, label: 'Handlebars', ace: 'handlebars', prism: null },
    { value: 36, label: 'Haskell', ace: 'haskell', prism: null },
    { value: 37, label: 'haXe', ace: 'haxe', prism: null },
    { value: 38, label: 'HTML', ace: 'html', prism: null },
    { value: 39, label: 'INI', ace: 'ini', prism: null },
    { value: 40, label: 'Io', ace: 'io', prism: null },
    { value: 41, label: 'Java', ace: 'java', prism: null },
    { value: 42, label: 'JavaScript', ace: 'javascript', prism: null },
    { value: 43, label: 'JSON', ace: 'json', prism: null },
    { value: 44, label: 'JSX', ace: 'jsx', prism: null },
    { value: 45, label: 'Julia', ace: 'julia', prism: null },
    { value: 46, label: 'Kotlin', ace: 'kotlin', prism: null },
    { value: 47, label: 'LaTeX', ace: 'latex', prism: null },
    { value: 48, label: 'LESS', ace: 'less', prism: null },
    { value: 49, label: 'Liquid', ace: 'liquid', prism: null },
    { value: 50, label: 'Lisp', ace: 'lisp', prism: null },
    { value: 51, label: 'LiveScript', ace: 'livescript', prism: null },
    { value: 52, label: 'Lua', ace: 'lua', prism: null },
    { value: 53, label: 'Makefile', ace: 'makefile', prism: null },
    { value: 54, label: 'Markdown', ace: 'markdown', prism: null },
    { value: 55, label: 'MATLAB', ace: 'matlab', prism: null },
    { value: 56, label: 'MEL', ace: 'mel', prism: null },
    { value: 57, label: 'MIXAL', ace: 'mixal', prism: null },
    { value: 58, label: 'MySQL', ace: 'mysql', prism: 'sql' },
    { value: 59, label: 'Nginx', ace: 'nginx', prism: null },
    { value: 60, label: 'Nix', ace: 'nix', prism: null },
    { value: 61, label: 'Nim', ace: 'nim', prism: null },
    { value: 62, label: 'NSIS', ace: 'nsis', prism: null },
    { value: 63, label: 'Objective-C', ace: 'objectivec', prism: null },
    { value: 64, label: 'OCaml', ace: 'ocaml', prism: null },
    { value: 65, label: 'Pascal', ace: 'pascal', prism: null },
    { value: 66, label: 'Perl', ace: 'perl', prism: null },
    { value: 67, label: 'pgSQL', ace: 'pgsql', prism: 'sql' },
    {
        value: 68,
        label: 'PHP (Blade Template)',
        ace: 'php_laravel_blade',
        prism: 'php'
    },
    { value: 69, label: 'PHP', ace: 'php', prism: null },
    { value: 70, label: 'Powershell', ace: 'powershell', prism: null },
    { value: 71, label: 'Prolog', ace: 'prolog', prism: null },
    { value: 72, label: 'Properties', ace: 'properties', prism: null },
    { value: 73, label: 'Protobuf', ace: 'protobuf', prism: null },
    { value: 74, label: 'Python', ace: 'python', prism: null },
    { value: 75, label: 'R', ace: 'r', prism: null },
    { value: 76, label: 'Ruby', ace: 'ruby', prism: null },
    { value: 77, label: 'Rust', ace: 'rust', prism: null },
    { value: 78, label: 'SASS', ace: 'sass', prism: null },
    { value: 79, label: 'Scala', ace: 'scala', prism: null },
    { value: 80, label: 'Scheme', ace: 'scheme', prism: null },
    { value: 81, label: 'SCSS', ace: 'scss', prism: null },
    { value: 82, label: 'SH', ace: 'sh', prism: null },
    { value: 83, label: 'Smarty', ace: 'smarty', prism: null },
    { value: 84, label: 'SQL', ace: 'sql', prism: null },
    { value: 85, label: 'SQLServer', ace: 'sqlserver', prism: 'sql' },
    { value: 86, label: 'Stylus', ace: 'stylus', prism: null },
    { value: 87, label: 'SVG', ace: 'svg', prism: null },
    { value: 88, label: 'Swift', ace: 'swift', prism: null },
    { value: 89, label: 'Tcl', ace: 'tcl', prism: null },
    { value: 90, label: 'Terraform', ace: 'terraform', prism: null },
    { value: 91, label: 'Text', ace: 'text', prism: null },
    { value: 92, label: 'Textile', ace: 'textile', prism: null },
    { value: 93, label: 'Toml', ace: 'toml', prism: null },
    { value: 94, label: 'TSX', ace: 'tsx', prism: null },
    { value: 95, label: 'Twig', ace: 'twig', prism: null },
    { value: 96, label: 'Typescript', ace: 'typescript', prism: null },
    { value: 97, label: 'Vala', ace: 'vala', prism: null },
    { value: 98, label: 'VBScript', ace: 'vbscript', prism: 'vb' },
    { value: 99, label: 'Velocity', ace: 'velocity', prism: null },
    { value: 100, label: 'Verilog', ace: 'verilog', prism: null },
    { value: 101, label: 'VHDL', ace: 'vhdl', prism: null },
    { value: 102, label: 'XML', ace: 'xml', prism: null },
    { value: 103, label: 'XQuery', ace: 'xquery', prism: null },
    { value: 104, label: 'YAML', ace: 'yaml', prism: null },
    { value: 105, label: 'Django', ace: 'django', prism: null }
];
